/**:
  ros__parameters:
    arena_x_min: 4.0
    arena_x_max: 7.0
    arena_y_min: 4.0
    arena_y_max: 7.0
    min_corridor_width: 0.5
    wall_breadth: 0.07
    wall_length: 1.0
    wall_num: 30
    